"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAccount } from "@/provider/account-provider";
import { AuthModal } from "@/components/auth/auth-modal";
import {
  HiOutlineBuildingOffice2,
  HiOutlineShoppingBag,
  HiOutlineArrowRight,
  HiOutlineArrowPathRoundedSquare,
  HiOutlinePlay,
  HiOutlineCpuChip,
  HiOutlineBookOpen,
} from "react-icons/hi2";
import type { ComponentType } from "react";

type Template = {
  id: string;
  name: string;
  slug: string;
  category: string;
  description: string;
  icon: ComponentType<{ className?: string }>;
  active: boolean;
};

const templates: Template[] = [
  {
    id: "1a43ds8pqw",
    name: "City Travel Guide",
    slug: "city-travel-guide",
    category: "Travel",
    icon: HiOutlineBuildingOffice2,
    description:
      "A conversational voice tour guide for a city. Provides information on landmarks, directions, and local tips to tourists.",
    active: true,
  },
  {
    id: "2b34ds9qwe",
    name: "Restaurant Assistant",
    slug: "restaurant-assistant",
    category: "Customer Support",
    icon: HiOutlineCpuChip,
    description:
      "An agent that answers the phone to help customers check reservations and bookings. It can handle inquiries about menu, hours, and location.",
    active: false,
  },
  {
    id: "3c56df7asd",
    name: "Language Practice Coach",
    slug: "language-practice-coach",
    category: "Creative",
    icon: HiOutlineBookOpen,
    description:
      "A voice AI agent that helps users practice speaking a new language through live and interactive conversation.",
    active: true,
  },
  {
    id: "4d78gh6fgh",
    name: "Product Advisor",
    slug: "product-advisor",
    category: "Customer Support",
    icon: HiOutlineShoppingBag,
    description:
      "An assistant that helps users choose the right product, provide recommendations, and guide users through the buying process.",
    active: false,
  },
];

export function TemplateSection() {
  const { account, user } = useAccount();
  const router = useRouter();
  const [authOpen, setAuthOpen] = useState(false);
  const closeAuth = useCallback(() => setAuthOpen(false), []);

  const handleRemix = (templateId: string) => {
    if (!user) {
      setAuthOpen(true);
      return;
    }
    if (account && account.is_active === false) {
      router.push("/beta-access");
      return;
    }
    if (account && account.is_active === true) {
      router.push(`/project/${templateId}?remix=true`);
      return;
    }
    return;
  };

  return (
    <>
      <section id="templates" className="mx-auto w-full max-w-7xl px-6 py-32">
        <div
          data-aos="fade-up"
          className="mb-16 flex flex-col justify-between gap-4 md:flex-row md:items-end"
        >
          <div>
            <h2 className="mb-4 text-3xl font-bold">Discover Templates</h2>
            <p className="max-w-md text-muted-foreground">
              Explore high fidelity agents generated by the community using
              natural language prompts.
            </p>
          </div>
          <Link
            href="/templates"
            className="inline-flex items-center gap-2 text-base font-semibold text-primary transition-colors hover:text-primary/80"
          >
            View all templates
            <HiOutlineArrowRight className="h-4 w-4" />
          </Link>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {templates.map((t, i) => (
            <div key={t.id} data-aos="fade-up" data-aos-delay={String(i * 100)}>
              <TemplateCard template={t} onRemix={handleRemix} />
            </div>
          ))}
        </div>
      </section>
      <AuthModal open={authOpen} onClose={closeAuth} />
    </>
  );
}

function TemplateCard({
  template,
  onRemix,
}: {
  template: Template;
  onRemix: (id: string) => void;
}) {
  const Icon = template.icon;
  return (
    <article className="group flex flex-col rounded-2xl border border-border bg-surface/40 transition-all hover:border-primary/50 hover:bg-surface/60 hover:shadow-[0_0_30px_rgba(17,82,212,0.10)] hover:ring-1 hover:ring-primary/20">
      {/* Visual header */}
      <div className="relative flex h-32 items-center justify-center overflow-hidden rounded-t-2xl bg-surface-elevated/50">
        <Icon className="h-10 w-10 text-muted-foreground/20 transition-transform group-hover:scale-110" />
        <Waveform
          active={template.active}
          className="absolute bottom-3 right-3"
        />
      </div>

      {/* Content */}
      <div className="flex flex-1 flex-col p-5">
        <p className="mb-1 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
          {template.category}
        </p>
        <h3 className="mb-1.5 text-base font-bold">{template.name}</h3>
        <p className="mb-4 flex-1 text-sm leading-relaxed text-muted-foreground">
          {template.description}
        </p>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => onRemix(template.id)}
            className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-border bg-surface-elevated/30 px-5 py-2 text-xs font-bold whitespace-nowrap transition-all hover:bg-foreground hover:text-background active:scale-[0.98]"
          >
            <HiOutlineArrowPathRoundedSquare className="h-3.5 w-3.5" />
            Remix
          </button>
          {template.active ? (
            <Link
              href={`/discover/${template.slug}`}
              target="_blank"
              className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface-elevated/30 px-5 py-2 text-xs font-bold whitespace-nowrap transition-all hover:bg-foreground hover:text-background active:scale-[0.98]"
            >
              <HiOutlinePlay className="h-3.5 w-3.5" />
              Try Live
            </Link>
          ) : (
            <span className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface-elevated/30 px-5 py-2 text-xs font-bold whitespace-nowrap text-muted-foreground/40 cursor-not-allowed">
              <HiOutlinePlay className="h-3.5 w-3.5" />
              Try Live
            </span>
          )}
        </div>
      </div>
    </article>
  );
}

function Waveform({
  active,
  className = "",
}: {
  active: boolean;
  className?: string;
}) {
  const heights = active
    ? ["h-2", "h-5", "h-3", "h-4", "h-2"]
    : ["h-3", "h-3", "h-3", "h-3", "h-3"];
  return (
    <div
      className={`waveform ${active ? "text-secondary" : "text-primary"} ${className}`}
      aria-hidden
    >
      {heights.map((h, i) => (
        <span
          key={i}
          className={`bar ${h} ${active ? "animate-pulse" : "opacity-40"}`}
        />
      ))}
    </div>
  );
}
